const LOG_IN = 'LOG_IN';
const EDIT_PROFILE_NAME = 'EDIT_PROFILE_NAME';
const EDIT_PROFILE_PICTURE = 'EDIT_PROFILE_PICTURE';
const DISPLAY_MATCHES = 'DISPLAY_MATCHES';
const DISPLAY_LIKES = 'DISPLAY_LIKES';
const DISPLAY_EXPLORE = 'DISPLAY_EXPLORE';
const GITHUB_TOKEN = 'GITHUB_TOKEN';
const UPDATE_USER = 'UPDATE_USER';
const UPDATE_EXPLORE = 'UPDATE_EXPLORE';
const UPDATE_MATCHES = 'UPDATE_MATCHES';
const UPDATE_LIKEDBY = 'UPDATE_LIKEDBY';

module.exports={
  LOG_IN,
  EDIT_PROFILE_NAME,
  EDIT_PROFILE_PICTURE,
  DISPLAY_MATCHES,
  DISPLAY_LIKES,
  DISPLAY_EXPLORE,
  GITHUB_TOKEN,
  UPDATE_USER,
  UPDATE_EXPLORE,
  UPDATE_LIKEDBY,
  UPDATE_MATCHES
}